# Generated by Django 5.0.1 on 2024-02-12 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userprofile1_delete_userprofile'),
        ('products', '0004_delete_product_delete_product1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile1',
            name='product_favorites',
            field=models.ManyToManyField(to='products.product2'),
        ),
    ]
